### ISSUE TITLE
Only 19 bits read

### ISSUE THREAD

**Issue by aFooBar** [nobodyguy/weighty#1]
I've updated your project to build in SES and use my pins.
I've a HX711 chip connected to the nRF52 DK to pins 0.26/0.27.
Got permanent error : 
> <info\> hx711: Number of bits : 19

Did you succeed in reading the 24 bits with the HX711 lib from Nordic Devzone ?

**Comment by nobodyguy** [comment]
Hi, yes, it worked for me quite well. I didn't face this issue.
I had hard times with all the noise, but that's understandable based on my poor knowledge of the topic and my breadboard setup.
I've abandoned this project because I don't have enough time to get into this topic and develop as precise scale as I would want.
But I've been working on similar pet project (where the precision requirement is not that strict) and my plan is to use Zephyr.
Check this PR, hx711 driver is about to get merged into mainline - https://github.com/zephyrproject-rtos/zephyr/pull/24295
